steps:

# Install dependencies and run tests
- name: 'python:3.12'
  entrypoint: bash
  args:
    - -c
    - |
      pip install -r requirements.txt
      pytest
  options:
  logging: CLOUD_LOGGING_ONLY

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$SHORT_SHA'
    - '.'

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$SHORT_SHA'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - my-scalable-app
    - --image=asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$SHORT_SHA
    - --region=asia-south1
    - --platform=managed
    - --allow-unauthenticated

images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-repo/my-app:$SHORT_SHA'